# -*- coding: utf-8 -*-
"""arbitrary

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X68Z2oTMK_FQn_x0B2OkbChGcuE7yf3s
"""



# arbitrary.py - Procesado y guardado unificado (6 columnas)
import numpy as np
import functions

# Configuración inicial
vec = ([-1, 1, 0.3, -1.5, 5, 0.6, -0.2, 0.25, 0.1, -0.2])
results = [[0, 0, 0, 0]]
status = [0]
params, couplings = functions.GenParams(vec)
index = 0

#  CICLO DE SIMULACIÓN
# np.linspace(inicio, fin, pasos)
for i in np.linspace(0, 15, 1000):
    print("T = ", i)
    # Definición de variables: [q+, q-, T, epsilon]
    variables = np.array([
        np.max([np.random.rand()*100, results[index][0]]),
        np.max([np.random.rand()*100, results[index][1]]),
        i,
        np.max([np.random.rand()*100, results[index][3]])
    ])

    # Minimización de energía
    prov = functions.MinimizeEnergy(params, variables, couplings, mask=np.array([1, 1, 0, 1]), verbose=False, cycles=2000, delta=1e-16)

    results.append(prov[1])
    status.append(prov[0])
    index += 1

#PROCESAMIENTO DE DATOS PARA GUARDADO
results_np = np.array(results)
status_np = np.array(status).reshape(-1, 1) # Convertimos a columna vertical

# Calculamos la energía libre para cada fila (mismo tamaño que las iteraciones)
energy_np = np.zeros((len(results_np), 1))
for i in range(len(results_np)):
    energy_np[i] = functions.FreeEnergy(params, results_np[i], couplings)

# Unimos todo en una matriz de 6 columnas:
# Col 0:q+ | Col 1:q- | Col 2:T | Col 3:epsilon | Col 4:status | Col 5:free_energy
datos_totales = np.hstack([results_np, status_np, energy_np])

# GENERACIÓN DEL HEADER
# Construimos el string con los parámetros del vector vec
header_txt = (
    f"Parametros de la simulacion:\n"
    f"# a+={vec[0]}, T+={vec[1]}, b+={vec[2]}, a-={vec[3]}, T-={vec[4]}\n"
    f"# b-={vec[5]}, c={vec[6]}, k={vec[7]}, lambda+={vec[8]}, lambda-={vec[9]}\n"
    f"# Columnas: q+  q-  T  epsilon  status  free_energy"
)

# Guardado final con formato de 8 decimales (%2.8f)
np.savetxt('datos_simulacion.txt', datos_totales, header=header_txt, fmt='%2.8f')

print("--------------------------------------------------")
print("Simulación finalizada exitosamente.")
print("Archivo 'datos_simulacion.txt' generado con 6 columnas.")
print("--------------------------------------------------")