# -*- coding: utf-8 -*-
"""plots

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZlmwlJwHaw0iKazKy2YnNeHIDm-6tZp3
"""

import numpy as np
import matplotlib.pyplot as plt

# 1. Cargamos el archivo único de 6 columnas
data = np.loadtxt('datos_simulacion.txt')

# 2. SEPARACIÓN DE DATOS (Mapeo de las 6 columnas)
# Col 0:q+, Col 1:q-, Col 2:T, Col 3:epsilon, Col 4:status, Col 5:energy
results = data[:, 0:4]  # Toma las primeras 4 columnas (q+, q-, T, epsilon)
status  = data[:, 4]    # Toma la quinta columna (status de error)
energy  = data[:, 5]    # Toma la sexta columna (energía libre)

vec = ([-1, 1, 0.3, -1.5, 5, 0.6, -0.7, 0.25, 0.1, -0.2])

# --- BLOQUE DE GRÁFICAS ORIGINAL ---
fig, ax = plt.subplot_mosaic([[0, 1],
                               [2, 2]],
                              figsize=(9, 6), layout="constrained")

# Identificamos errores usando la columna status que ya cargamos
errors = results[np.where(status != 0)]

# Gráfica q+ (Columna 2 de results es T, Columna 0 es q+)
ax[0].scatter(results[:,2], results[:,0],s=4,color="black")
ax[0].scatter(errors[:,2], errors[:,0], color="red",s=4)
ax[0].set_ylabel(r'$q_+$')

# Gráfica q- (Columna 1 de results es q-)
ax[1].scatter(results[:,2], results[:,1],s=4,color="black")
ax[1].scatter(errors[:,2], errors[:,1], color="red",s=4)
ax[1].set_ylabel(r'$q_-$')

# Gráfica epsilon (Columna 3 de results es epsilon)
ax[2].scatter(results[:,2], results[:,3],s=4,color="black")
ax[2].scatter(errors[:,2], errors[:,3], color="red",s=4)
ax[2].set_ylabel(r'$\epsilon$')

# Líneas verticales de referencia
for i in range(0, 3):
    ax[i].plot([vec[1], vec[1]], [np.min(results[:,i+(int(i/2))]), np.max(results[:,i+(int(i/2))])], linestyle="--", color="blue")
    ax[i].plot([vec[4], vec[4]], [np.min(results[:,i+(int(i/2))]), np.max(results[:,i+(int(i/2))])], linestyle="--", color="blue")

# --- GRÁFICO DE ENERGÍA (AHORA MÁS RÁPIDO) ---
# Ya no usamos el bucle for ni functions.FreeEnergy porque ya tenemos 'energy'
fig, ax_en = plt.subplots()
ax_en.scatter(results[:, 2], energy,s=4,color="black") # results[:, 2] es la temperatura T
ax_en.set_xlabel("T")
ax_en.set_ylabel("Free Energy")

plt.show()