# -*- coding: utf-8 -*-
"""pressure.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j3CXegsKhps1MoDg1KCeRqGrhI0c2iTw
"""

# Commented out IPython magic to ensure Python compatibility.
# 
# %%writefile pressure.py
# 
# # ==========================================================
# # pressure.py
# #
# # Simulacion de diagramas de fase Presion-Temperatura
# # usando el modelo Landau 2t66p
# #
# # El objetivo es identificar las regiones donde:
# #
# # Fase 0 -> q+ = 0  y q- = 0
# # Fase 1 -> q+ != 0 y q- = 0
# # Fase 2 -> q+ = 0  y q- != 0
# # Fase 3 -> q+ != 0 y q- != 0
# #
# # y construir un mapa de color en el plano (T,P)
# # ==========================================================
# 
# import numpy as np
# import matplotlib.pyplot as plt
# import functions
# 
# # ==========================================================
# # PARAMETROS DEL MODELO
# # ==========================================================
# 
# # Orden:
# # [a+, T+, b+, a-, T-, b-, c, k,
# #  lambda+, lambda-, d+, d-, kp]
# 
# vecP = np.array([
# 
#     1,        # a+
#     200,      # T+
#     3000,     # b+
# 
#     0.4,      # a-
#     800,      # T-
#     200,      # b-
# 
#     300,      # c
#     70,       # k
# 
#     2,        # lambda+  (positivo)
#     -10,      # lambda-  (negativo)
# 
#     260,      # d+
#     2500,     # d-
# 
#     1         # kp
# ])
# 
# # ==========================================================
# # GENERAR PARAMETROS DE ENERGIA LIBRE
# # ==========================================================
# 
# paramsP, couplingsP = functions.GenParams(
#     vecP,
#     model="2t66p"
# )
# 
# # ==========================================================
# # MALLA DE TEMPERATURA Y PRESION
# # ==========================================================
# 
# # Puedes aumentar estos numeros para mejor resolucion
# 
# temperaturas = np.linspace(0,1500,30)
# 
# presiones = np.linspace(0,10,30)
# 
# # ==========================================================
# # ARRAY DONDE GUARDAREMOS:
# #
# # T | P | fase
# # ==========================================================
# 
# mapa = []
# 
# print("====================================")
# print("SIMULACION PRESION-TEMPERATURA")
# print("====================================")
# 
# # ==========================================================
# # CICLO PRINCIPAL
# # ==========================================================
# 
# for T in temperaturas:
# 
#     print("Temperatura =", T)
# 
#     for P in presiones:
# 
#         # ==============================================
#         # Variables iniciales:
#         #
#         # [q+, q-, T, epsilon, P]
#         # ==============================================
# 
#         variables = np.array([
# 
#             1,      # q+
#             1,      # q-
#             T,      # temperatura
#             0.1,    # epsilon
#             P       # presion
#         ])
# 
#         # ==============================================
#         # MINIMIZACION DE ENERGIA LIBRE
#         # ==============================================
# 
#         prov = functions.MinimizeEnergy(
# 
#             paramsP,
#             variables,
#             couplingsP,
# 
#             # minimizar sobre:
#             # q+, q-, epsilon
#             # NO sobre T ni P
# 
#             mask=np.array([1,1,0,1,0]),
# 
#             verbose=False,
#             warnings=False,
# 
#             cycles=1000
#         )
# 
# 
#         # SOLUCION ENCONTRADA
# 
# 
#         qp = abs(prov[1][0])
# 
#         qm = abs(prov[1][1])
# 
#         # tolerancia numerica
#         tol = 1e-3
# 
#         # IDENTIFICACION DE FASE
#         # ----------------------------------------------
#         # FASE 0
#         #
#         # q+ = 0
#         # q- = 0
# 
# 
#         if qp < tol and qm < tol:
# 
#             fase = 0
# 
# 
#         # FASE 1
#         #
#         # q+ != 0
#         # q- = 0
# 
# 
#         elif qp > tol and qm < tol:
# 
#             fase = 1
# 
# 
#         # FASE 2
#         #
#         # q+ = 0
#         # q- != 0
# 
# 
#         elif qp < tol and qm > tol:
# 
#             fase = 2
# 
#         # FASE 3
#         #
#         # q+ != 0
#         # q- != 0
# 
# 
#         else:
# 
#             fase = 3
# 
#         # Guardar:
#         #
#         # temperatura
#         # presion
#         # fase
# 
#         mapa.append([T,P,fase])
# 
# 
# # CONVERTIR A ARRAY NUMPY
# 
# 
# mapa = np.array(mapa)
# 
# # GUARDAR DATOS
# 
# 
# np.savetxt(
# 
#     "datos_presion.txt",
# 
#     mapa,
# 
#     header="T   P   fase",
# 
#     fmt='%2.8f'
# )
# 
# print("====================================")
# print("datos_presion.txt generado")
# print("====================================")
# 
# # ==========================================================
# # GRAFICA DEL MAPA DE FASES
# 
# 
# # Reorganizar datos
# 
# T_vals = mapa[:,0]
# 
# P_vals = mapa[:,1]
# 
# fases = mapa[:,2]
# 
# # Convertir a malla 2D
# 
# T_grid = T_vals.reshape(len(temperaturas),len(presiones))
# 
# P_grid = P_vals.reshape(len(temperaturas),len(presiones))
# 
# fase_grid = fases.reshape(len(temperaturas),len(presiones))
# 
# 
# # MAPA DE COLOR
# 
# 
# fig, ax = plt.subplots(figsize=(8,6))
# 
# 
# # COLORES DE CADA FASE
# #
# # white  -> fase 0
# # blue   -> fase 1
# # red    -> fase 2
# # green  -> fase 3
# 
# 
# cmap = plt.matplotlib.colors.ListedColormap([
# 
#     "white",   # fase 0 -> q+=0  q-=0
# 
#     "blue",    # fase 1 -> q+!=0 q-=0
# 
#     "red",     # fase 2 -> q+=0  q-!=0
# 
#     "green"    # fase 3 -> q+!=0 q-!=0
# ])
# 
# graf = ax.pcolormesh(
# 
#     T_grid,
#     P_grid,
#     fase_grid,
# 
#     shading='auto',
# 
#     cmap=cmap
# )
# 
# 
# ax.set_xlabel("Temperatura")
# 
# ax.set_ylabel("Presion")
# 
# ax.set_title("Diagrama de fases Presion-Temperatura")
# 
# cbar = plt.colorbar(graf)
# 
# cbar.set_ticks([0,1,2,3])
# 
# cbar.set_ticklabels([
# 
#     r'q+=0 , q-=0',
# 
#     r'q+≠0 , q-=0',
# 
#     r'q+=0 , q-≠0',
# 
#     r'q+≠0 , q-≠0'
# ])
# 
# plt.show()