# -*- coding: utf-8 -*-
"""pressurefull

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KOSHbGTulIV-YoBNJm5BDm7Zi9714SgL
"""

import numpy as np
import functions
# PARTE 1: SIMULACION ORIGINAL
vec = ([-1, 1, 0.3, -1.5, 5, 0.6, -0.2, 0.25, 0.1, -0.2])

results = [[0,0,0,0]]
status = [0]

params, couplings = functions.GenParams(vec)

index = 0

print("====================================")
print("SIMULACION TEMPERATURA")
print("====================================")

for i in np.linspace(0,15,10):

    print("T =", i)

    variables = np.array([
        np.max([np.random.rand()*100, results[index][0]]),
        np.max([np.random.rand()*100, results[index][1]]),
        i,
        np.max([np.random.rand()*100, results[index][3]])
    ])

    prov = functions.MinimizeEnergy(
        params,
        variables,
        couplings,
        mask=np.array([1,1,0,1]),
        verbose=False,
        cycles=120,
        delta=1e-16
    )

    results.append(prov[1])
    status.append(prov[0])

    index += 1

results_np = np.array(results)
status_np = np.array(status).reshape(-1,1)

energy_np = np.zeros((len(results_np),1))

for i in range(len(results_np)):

    energy_np[i] = functions.FreeEnergy(
        params,
        results_np[i],
        couplings
    )

datos_totales = np.hstack([
    results_np,
    status_np,
    energy_np
])

np.savetxt(
    "datos_simulacion.txt",
    datos_totales,
    fmt='%2.8f'
)

print("datos_simulacion.txt generado")

# PARTE 2: MAPA PRESION-TEMPERATURA

print("====================================")
print("SIMULACION PRESION-TEMPERATURA")
print("====================================")

# Nuevo modelo con terminos de sexto orden y kp
# vecP = np.array([
#     1.00000,   # a+
#     72.3667,   # T+
#     8696.34,   # b+
#     0.093518,  # a-
#     1544.00,   # T-
#     53.2236,   # b-
#     -912.57,   # c
#     1510.22,   # k
#     -375.67,   # lambda+
#     71.2780,   # lambda-
#     115.844,   # d+
#     11.6535,   # d-
#     100.0      # kp (valor elegido)
# ])

# ==========================================================
# CASO Ba2BiSbO6 con reescalamiento de parámetros

mult = 3000

a0 = 1.55

b_0 = (
    510.594*a0
    + ((11.9192*mult)**2)/(87.8169*mult)
    - ((11.9192)**2)/(87.8169)
)

vecP = np.array([

    # a+, T+, b+
    0.00000,
    0.00000,
    0.00000,

    # a-, T-, b-
    1.55369491e+00,
    510.594,
    b_0,

    # c
    0.00000,

    # k
    87.8169*mult,

    # lambda+
    0.00000,

    # lambda-
    -11.9192*mult,

    # d+
    0.00000,

    # d-
    5.32663570e+03,

    # kp
    2*(87.8169*mult/144)

])

paramsP, couplingsP = functions.GenParams(
    vecP,
    model="2t66p"
)

mapa = []

temperaturas = np.linspace(0,1500,40)
presiones = np.linspace(0,10,40)

for T in temperaturas:

    print("Temperatura =", T)

    for P in presiones:

        variables = np.array([
            1,
            1,
            T,
            0.1,
            P
        ])

        prov = functions.MinimizeEnergy(
            paramsP,
            variables,
            couplingsP,
            mask=np.array([1,1,0,1,0]),
            verbose=False,
            cycles=120,
            delta=1e-6
        )

        qp = abs(prov[1][0])
        qm = abs(prov[1][1])

        tol = 1e-3

        if qp < tol and qm < tol:
            fase = 0

        elif qp > tol and qm < tol:
            fase = 1

        elif qp < tol and qm > tol:
            fase = 2

        else:
            fase = 3

        mapa.append([T,P,fase])

mapa = np.array(mapa)

np.savetxt(
    "datos_presion.txt",
    mapa,
    fmt='%2.8f'
)

print("datos_presion.txt generado")

print("====================================")
print("SIMULACION TERMINADA")
print("====================================")

import numpy as np
import matplotlib.pyplot as plt

# GRAFICAS ORIGINALES
data = np.loadtxt("datos_simulacion.txt")

results = data[:,0:4]
status = data[:,4]
energy = data[:,5]

vec = ([-1, 1, 0.3, -1.5, 5, 0.6, -0.2, 0.25, 0.1, -0.2])

fig, ax = plt.subplot_mosaic(
    [[0,1],
     [2,2]],
    figsize=(9,6),
    layout="constrained"
)

errors = results[np.where(status != 0)]

# q+
ax[0].scatter(results[:,2], results[:,0], s=4, color="black")
ax[0].scatter(errors[:,2], errors[:,0], s=4, color="red")
ax[0].set_ylabel(r"$q_+$")

# q-
ax[1].scatter(results[:,2], results[:,1], s=4, color="black")
ax[1].scatter(errors[:,2], errors[:,1], s=4, color="red")
ax[1].set_ylabel(r"$q_-$")

# epsilon
ax[2].scatter(results[:,2], results[:,3], s=4, color="black")
ax[2].scatter(errors[:,2], errors[:,3], s=4, color="red")
ax[2].set_ylabel(r"$\epsilon$")
ax[2].set_xlabel("T")

for i in range(0,3):

    ax[i].plot(
        [vec[1], vec[1]],
        [np.min(results[:,i]), np.max(results[:,i])],
        linestyle="--",
        color="blue"
    )

    ax[i].plot(
        [vec[4], vec[4]],
        [np.min(results[:,i]), np.max(results[:,i])],
        linestyle="--",
        color="blue"
    )


# ENERGIA LIBRE
fig2, ax2 = plt.subplots()

ax2.scatter(results[:,2], energy, s=4, color="black")

ax2.set_xlabel("T")
ax2.set_ylabel("Free Energy")

# MAPA DE FASES P-T
mapa = np.loadtxt("datos_presion.txt")

T = mapa[:,0]
P = mapa[:,1]
fase = mapa[:,2]

fig3, ax3 = plt.subplots(figsize=(8,6))

sc = ax3.scatter(
    T,
    P,
    c=fase,
    cmap="viridis",
    s=25
)

ax3.set_xlabel("Temperatura")
ax3.set_ylabel("Presion")

cbar = plt.colorbar(sc)

cbar.set_label("Fase")

plt.show()